GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjM0ODA3MTYzLCJleHAiOjE2MzQ4MDcxNzh9.UKbyzufdSLi3j1WrQbJm0Ah4Obth0W4WtNGiu3N16OU

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjM0ODA3MjAyfQ.LB_WY5L18_U3cS4EjVvHicPZf02kCXUS_suujGe4zuw"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjM0ODA3MjAyfQ.LB_WY5L18_U3cS4EjVvHicPZf02kCXUS_suujGe4zuw"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}